# fly.toml app configuration file generated for serializer-go on 2024-03-06T16:02:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'serializer-go'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
